version: "3"

services:
  web:
    image: psd:0.3
    command: gunicorn poker_stats_data.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: esolang/sqlite3
